### PR TITLE
Method `chunkwiseOverlap` improvement

### PR DESCRIPTION
**Pull request by Smoren**
All the `chunkwiseOverlap()` methods: optional param `$excludeIncompleteTail` is added.

I've found a usability problem with `chunkwiseOverlap()` function. There are cases when we don't want to get chunks with size less then `$chunkSize`. For example, you can see this case in `pairwise()` implementation. I've got this situation on getting triples.

I mean that when we use pairwise we do not want to get last chunk with only one element. And when we want to get overlapping triples we sometimes do not want to get pair or one item on the last iteration.

I've added an optional param `$excludeIncompleteTail` to solve it.

### CODE REVIEW

**Comment by markrogoyski** [comment]
Hi @Smoren,

Thank you for the PR. I understand the issue and how you are solving it.

My only feedback is rather than phrase it as a negative, consider phrasing it as a positive.

For example, right now the logic at the end of the method is `&& !$excludeIncompleteTail` which reads like "and not exclude," which sort of combines two negative statements, the "not" and the "exclude." Instead, how about phrasing in the positive: `&& includeIncompleteTail` to simplify the conditional logic to "and include". Similarly, the method would have a default value of `$includeIncompleteTail = true` rather than false.

What do you think?
Thanks,
Mark

**Comment by Smoren** [comment]
Hi @markrogoyski,

1. `$excludeIncompleteTail = false` param is renamed to `$includeIncompleteTail = true` for `Single::chunkwiseOverlap()` and `Stream::chunkwiseOverlap()`.
2. Tests are fixed about this param.

**Comment by Smoren** [comment]
Thank you Mark for merging this PR!

**Comment by markrogoyski** [comment]
Thank you for providing the improved functionality.

**Pull request merged**
