### PR TITLE
Method Single::filterUnique() added

### PR DESCRIPTION
**Pull request by Smoren**
- Method `Single::filterUnique()` added;
- Test `Single/FilterUniqueTest.php` added;
- README.md updated with description of new method.

### CODE REVIEW

**Comment by Smoren** [comment]
FYI: I moved unique-mapping logic to the separate repository: https://github.com/Smoren/unique-php

**Comment by Smoren** [comment]
@markrogoyski

Hi Mark!

FYI: I moved unique-mapping logic into the separate repository: https://github.com/Smoren/unique-php

Added missing behaviors and fixed bugs during testing.

**Comment by Smoren** [comment]
Rebased from branch "develop".

**Comment by Smoren** [comment]
@markrogoyski

FYI: I've moved `UniqueExtractor` from [unique-php](https://github.com/Smoren/unique-php) to [type-tools-php](https://github.com/Smoren/type-tools-php).

**Comment by Smoren** [comment]
Hi @markrogoyski 

I've rebased this branch from `develop` and resolved conflicts.

BTW I've a little bit changed [unique extracting logic](https://github.com/Smoren/type-tools-php/blob/master/src/UniqueExtractor.php) in my repo.

If you find a way to include this logic to IterTools we can implement such functionality as e. g. `Single::intersection()` and `Single::difference()`.

```php
use IterTools\Single;

$lhs = [1, 2, 3, 4, 5];
$rhs = [3, 4, 5, 6, 7];

$intersection = Single::intersection($lhs, $rhs);

foreach ($intersection as $item) {
    // 3, 4, 5
}
```

What do you think about it?

UPD: I've rebased this branch from `develop`.

**Comment by markrogoyski** [comment]
Hi @Smoren,

Apologies for the delay in responding.

How about changing the name to `distinct` and drop the "filter" prefix. Distinct usually means removing duplicates, whereas unique can imply only selecting the items that only appear once.

Thanks,
Mark

**Comment by Smoren** [comment]
Hi @markrogoyski 

Thank you for your suggestion!

Summary of changes:

1. `Single::filterUnique()` renamed to `Single::distinct()`.
2. `Util\UniqueExtractor` added and used in `Single::distinct()`.
3. `FilterUniqueTest` renamed to `DistinctTest`.
4. Tests added for resources, generators and closures.
5. `Stream::distinct()` method added and covered by tests.
6. README updated.

**Comment by Smoren** [comment]
BTW, what do you think about separate namespace for `distinct`, `intersection`, `difference` and other operations with sets?

**Comment by Smoren** [comment]
@markrogoyski 

BTW, what do you think about separate namespace for `distinct`, `intersection`, `difference` and other operations with sets?

**Comment by markrogoyski** [comment]
Hi @Smoren,

What is your suggestion here. Maybe `Set::distinct($data)`, `Set::intersection($set1, $set2)`, etc.?

**Comment by Smoren** [comment]
Hi @markrogoyski,

1. New namespace `Set` created.
2. Method `Single::distinct()` moved into namespace `Set`.
3. `DistinctTest` moved into `Set` directory.
4. Tests of `Stream::distinct()` moved into separate test `Stream\SetTest`.
5. README updated.

**Comment by Smoren** [comment]
UPD: this branch is rebased from `develop`.

**Pull request merged**
