### PR TITLE
`Set::distinctBy()`, `Stream::distinctBy()` added and tested.

### PR DESCRIPTION
**Pull request by Smoren**
Hi @markrogoyski,

I implemented `Set::distinctBy()`, `Stream::distinctBy()` methods and covered them with tests.

### CODE REVIEW

**Review by markrogoyski — APPROVED** [review]
Thanks for the pull request implementing `distinctBy`. Sorry for the long delay in reviewing this PR.

**Comment by Smoren** [comment]
Thank you @markrogoyski

**Comment by Smoren** [comment]
@markrogoyski, there is a mistake in docs. `Set::distinctBy()` does not support type coercion comparisons. 

image

**Comment by markrogoyski** [comment]
Thanks. Copy and paste mistake. I've updated the docs. Thanks for pointing it out.

**Pull request merged**
