### PR TITLE
`IteratorFactory::tee()` method added

### PR DESCRIPTION
**Pull request by Smoren**
Hi @markrogoyski,

I've implemented `IteratorFactory::tee()` method which is similar to python `tee()` function.

I think we can make `IteratorFactory` class non-internal because both of `makeIterator()` and `tee()` methods are quite abstract and useful for the client code.

BTW, we can implement method `Stream::tee()` to make new independent streams from the source one. Like this:

```php
public function tee(int $count): array
{
    return array_map(fn ($it) => new self($it), IteratorFactory::tee($this->iterable, $count));
}
```

And I think it's time to make `src/Util` directory less mixed. For example, we can move iterators to another directory — `src/Util/Iterators` or just `src/Iterators`, and `IteratorFactory` may be moved into `src` directory.

Thoughts?

### CODE REVIEW

**Comment by Smoren** [comment]
I've rebased this branch from `develop`.

**Comment by markrogoyski** [comment]
Hi @Smoren,

Thank you for the PR and implementing `tee`.

An interesting question is where does `tee` go. It doesn't quite fit the `Multi` namespace because those are iterating multiple iterables as input. It doesn't quite fit the `Single` namespace because those are iterating a single iterable as input and generally returning a new single iterable as output.

I will give this some thought. Thanks for your patience.
Mark

**Comment by Smoren** [comment]
Hi @markrogoyski,

I think the `IteratorFactory` is the best place for `tee()` method. And I think `IteratorFactory` have to be non-internal class.

BTW, what do you think about this?
> And I think it's time to make src/Util directory less mixed. For example, we can move iterators to another directory — src/Util/Iterators or just src/Iterators, and IteratorFactory may be moved into src directory.

**Comment by markrogoyski** [comment]
Hi @Smoren,

I agree that `Util` became a dumping ground for all the non-public interface classes. There seem to be two categories of classes in there: internal tools, and internal iterators. Separating these into different directories makes sense.

As an internal class, `IteratorFactory` is fine, but I don't think the name is clear and intuitive as a public interface.

Thinking about `tee`, it is kind of a transformation. It takes a single iterable and duplicates it. Would it be valuable to have other transformations? The `Stream` class already has some as in `toArray` and `toAssociativeArray` as terminal operations. Would it make sense in the loop iteration tools to have transformational tools like `Transform::toIterator`, `Transform::toArray` and such, and then `tee` could live in the same namespace as those transformations: `Transform:tee`. Just thinking out loud. Exposing a class called `IteratorFactor` that then has a method `tee` doesn't seem like the most intuitive and simple interface for someone to look at the name and immediately know what it does.

**Comment by Smoren** [comment]
Hi @markrogoyski,

There is summary of changes:

1. All the internal iterators have been moved to a separate namespace (`Util\Iterators`).
2. New namespace `Transform` has been added with methods `toArray()`, `toAssociativeArray()`, `toIterator()`, `tee()`.
3. `Stream::toArray()`, `Stream::toAssociativeArray()` implementations have been modified with using `Transform` methods.
4. `TeeTest`, `ToIteratorTest` have been moved into `tests/Transform` directory (`MakeIteratorTest` renamed to `ToIteratorTest`).
5. `IteratorFactory` removed.

**Comment by Smoren** [comment]
Hi @markrogoyski,

There is summary of changes:

1. All the internal iterators have been moved to a separate namespace (`Util\Iterators`).
2. New namespace `Transform` has been added with methods `toArray()`, `toAssociativeArray()`, `toIterator()`, `tee()`.
3. `Stream::toArray()`, `Stream::toAssociativeArray()` implementations have been modified with using `Transform` methods.
4. `Stream::tee()` method has been implemented and covered by tests.
5. `TeeTest`, `ToIteratorTest` have been moved into `tests/Transform` directory (`MakeIteratorTest` has been renamed to `ToIteratorTest`).
6. `IteratorFactory` has been removed.

**Comment by markrogoyski** [comment]
Hi @Smoren,

Thank you for making the changes and refactoring a lot of the classes.

I'm going to finish up some things with the currently-merged features and do a release before merging any other PRs. Apologies that I have not had the time to go over things as quickly as you make them. I'll try to get to them soon.

Thanks again for your patience and your continued development efforts.
Mark

**Comment by Smoren** [comment]
OK @markrogoyski. Sorry for taking up your time. Would it bother you if I keep opening pull requests for new features until you make a release?

**Comment by markrogoyski** [comment]
Hi @Smoren,

No need to apologize. It is not a bother. Thank you for continuing to provide improvements to IterTools.

Mark

**Comment by Smoren** [comment]
This branch is rebase from `develop`.

**Comment by Smoren** [comment]
Thanks for mering this PR!

**Pull request merged**
