### PR TITLE
Method `retro()` added to `Single` and `Stream` namespaces

### PR DESCRIPTION
**Pull request by Smoren**
Hi @markrogoyski,

I've added methods for reversing iterables.

Summary:
* `Single::retro()` method was added and tested;
* `Stream::retro()` method was added and tested.

### CODE REVIEW

**Comment by Smoren** [comment]
I've rebased this branch from `develop`.

**Comment by markrogoyski** [comment]
Hi @Smoren,

Thank you for the PR with the new functionality.

I think you probably want to call this `reverse` rather than `retro`. Retro means like old fashions from the past.

**Comment by Smoren** [comment]
Hi @markrogoyski,

I named the same as a similar function in [D language](https://dlang.org/library/std/range/retro.html).

But if you think that the name is not suitable, I will rename it.

**Comment by markrogoyski** [comment]
Hi @Smoren,

Names are hard, and often subjective. There is no single correct answer, only tradeoffs.

When thinking about a good name, I like to consider the intuitive discovery of the user, and prior art.

For something like reversing a list, I think most people would be searching for the word "reverse." Upon seeing a function called `reverse`, it would be clear what it does from the name alone. The name "reverse" leads to users discovering the functionality on their own. "Retro," on the other hand, is not intuitive, and it is unlikely that someone would be searching for that keyword for reverse functionality. Retro, in English, usually refers to older fashion made popular again, or an end-of-sprint meeting to discuss the previous work period (short for retrospective).

The other thing is prior art. [Most](https://docs.oracle.com/javase/7/docs/api/java/util/Collections.html#reverse(java.util.List)) [programming](https://docs.python.org/3/tutorial/datastructures.html) [languages](https://www.php.net/manual/en/function.array-reverse.php) [would](https://perldoc.perl.org/functions/reverse) [call](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/reverse) [this](https://www.geeksforgeeks.org/ruby-array-reverse-function/) [functionality](https://learn.microsoft.com/en-us/dotnet/api/system.array.reverse?source=recommendations&view=net-7.0) `reverse`. Even D has a method called [reverse](https://dlang.org/library/std/algorithm/mutation/reverse.html). Therefore, I think both intuitive discovery and prior art point to "reverse" being the appropriate name here.

In your other PR, `tee` on the other hand I think would favor prior art over discoverability. Tee is common enough in the Linux/Unix CLI and some programming languages, that even though it may not be the intuitive name a less-experienced programmer would search for, it is the established name for duplicating input to multiple targets. While something like `duplicate` might be what someone may search for, `tee` is the established name here, and I would go with `tee` for that function. Another example, if someone didn't know what a regular expression was, they might search for "pattern matching" or something, but regex is the established name for this, so prior art wins.

**Comment by Smoren** [comment]
Hi @markrogoyski,

Agree with you. I'll rename this method when I get access to my PC.

**Comment by Smoren** [comment]
And another point. What do you think about making a new interface for iterators named `BidirectionalIterator` and reduce `reverse()` memory usage for it's instances?

**Comment by Smoren** [comment]
Hi @markrogoyski,

I've renamed `retro()` to `reverse()`.

BTW, what do you think about making a new interface for iterators named `BidirectionalIterator` and reduce `reverse()` memory usage for it's instances?

**Comment by Smoren** [comment]
Hi @markrogoyski,

I've rebase this branch from `develop` and resolved the confilcts.

**Comment by Smoren** [comment]
This branch is rebased from `develop`, conflicts are resoved.

**Comment by markrogoyski** [comment]
Thanks for adding `reverse` and iterating on the naming.

**Comment by Smoren** [comment]
Thanks Mark for merging this PR!

**Pull request merged**
