### PR TITLE
`Single::slice()` method added

### PR DESCRIPTION
**Pull request by Smoren**
Hi @markrogoyski,

I've added `Single::slice()` and `Stream::slice()` methods and covered them with tests.

### CODE REVIEW

**Comment by Smoren** [comment]
This branch is rebase from `develop`.

**Comment by Smoren** [comment]
I've rebased this branch from `develop` and resolved the conflicts.

**Comment by markrogoyski** [comment]
Hi @Smoren,

Thank you for the PR adding slice functionality. It is interesting that you added a step function like Python. PHP's built-in `array_slice` does not have that feature, so it is a nice improvement.

Question: It is not clear what the desired behavior is if either `$count` or `$step` are negative values. This should be documented and have unit tests. It seems like a negative value for `$step` or `$count` should be an error and rejected as bad input, as it doesn't make a lot of sense to count a negative amount or step in a negative amount. What do you think?

Thanks,
Mark

**Comment by Smoren** [comment]
Hi @markrogoyski,

Do you think that it is not enough to specify the scope of parameters in phpdoc?

```php
/*
 * ...
 * @param int<0, max> $start
 * @param int<0, max>|null $count
 * @param positive-int $step
 * ...
 */
```

**Comment by markrogoyski** [comment]
As a general programming rule, you don't want to allow invalid state to be representable. It is better to fail at the first sign of invalid input, rather than producing a nonsensical result that could then be passed further down into the program, without knowing that it is working with invalid results. If you don't error out as early as possible, you risk passing on invalid data over the network to another system, or inserting it into a database, or silently just using it without ever knowing it is wrong. Trying to troubleshoot and find the root cause of a data error that didn't error our and got passed around to various systems is next to impossible sometimes because there is no indication that something was wrong. But somewhere, something is not going to look quite right, but how would you know.

Since the PHP type system cannot help us here, I think you have to manually check for invalid input and throw an exception.

Another way to think of it: you want any client of this function to trust the result. They shouldn't have to question whether it is working. If the client provides invalid data, just fail and inform them immediately.

**Comment by Smoren** [comment]
Hi @markrogoyski,

I've added and tested params validation.

**Comment by markrogoyski** [comment]
Thanks for adding input validation.

**Comment by Smoren** [comment]
Thank you for merging this PR!

**Pull request merged**
