### PR TITLE
README translation is complete, some fixes in main README file made.

### PR DESCRIPTION
**Pull request by Smoren**
Hi @markrogoyski,

I've finished Russian README translation for v1.4.0.

And I've fixed several mistakes in main README file.

### CODE REVIEW

**Comment by markrogoyski** [comment]
Hi @Smoren.

Thank you so much for updating the translation!

**Comment by Smoren** [comment]
Thank you Mark!

**Comment by Smoren** [comment]
Hi @markrogoyski,

Can you please rebase `develop` branch from `main`?

**Comment by markrogoyski** [comment]
I've merged the changes from `main` into `develop`. Sorry for forgetting to do this after merging.

**Comment by Smoren** [comment]
Thank you Mark!

**Pull request merged**
