### PR TITLE
Test cases for 1-partial intersections of multisets

### PR DESCRIPTION
**Pull request by Smoren**
`Set::intersectionPartial()` test cases added for multisets with `$minIntersectionCount = 1`.

Explanation of the behavior:

* N — size of initial collections;
* M — min intersection count.

For any N when M = 1 we have a union of sets or multisets.

image

Some examples of multiset unions from [this article](https://trizenx.blogspot.com/2016/05/multisets.html?m=1):

* `[1, 2] ∪ [1] = [1, 2]`;
* `[1, 2] ∪ [1, 1] = [1, 1, 2]`;
* `[1, 1] ∪ [1, 1, 1, 2] = [1, 1, 1, 2]`.

I've added test cases for this examples and some more complicated cases. They all work predictably.

### CODE REVIEW

**Comment by markrogoyski** [comment]
Thanks for the explanation and examples. From what I understand, a union of a multiset is really taking the item from the set that has the max cardinality, rather than "adding" them all together. Your examples show the same thing. Thanks.

**Comment by Smoren** [comment]
OK. I'm glad that we have come to a common perception of this functionality.

You can merge this PR if you want to add the tests included in it.

**Comment by Smoren** [comment]
BTW, I was very surprised that the concept of partial intersection was not defined in math. I consulted with mathematician friends and decided to write an article on this topic.

Thank you for the inspiration!

**Comment by Smoren** [comment]
Hi @markrogoyski,

FYI: I've created a [new repository](https://github.com/Smoren/partial-intersection-php) with explanation and examples of the partial intersection.

**Pull request merged**
