### PR TITLE
Method Reduce::toVectorLength() added

### PR DESCRIPTION
**Pull request by Smoren**
1. Methods `Reduce::toVectorLength()` and `Stream::toVectorLength()` added.
2. Tests added for new methods.
3. README updated with description of new methods.

### CODE REVIEW

**Comment by Smoren** [comment]
I've rebased this branch from `develop`.

**Comment by Smoren** [comment]
I've rebased this branch from `develop` again and resolved the conflicts.

**Comment by markrogoyski** [comment]
Hi @Smoren,

Thank you for the feature suggestion and PR.

Question: Do you think this would be widely applicable to many use cases? I would think that if someone is doing linear algebra with vectors they would be using a mathematics library like [MathPHP](https://github.com/markrogoyski/math-php) which has Vectors that implement the l2-norm length already. What would be the use case where someone would use this functionality in IterTools over MathPHP?

Thanks,
Mark

**Comment by Smoren** [comment]
OK, if you think that this is not a very useful feature, I close the PR.

**Pull request closed without merging**
